### ISSUE TITLE
Suggestion: Customisable number of modules

### ISSUE THREAD

**Issue by Stefanos423** [Naouak/marvel-lcg-randomizer#1]
I suggest allowing the users to select the number of modules they would like to add in their randomised encounter deck. Most of the code to implement this functionality is already in place.

![image](https://user-images.githubusercontent.com/15016302/71190895-48736580-227d-11ea-876a-8fcc9b81eff8.png)

**Comment by Naouak** [comment]
Yes, I have planned to add that feature but There is still the issue of Wrecking Crew that's bothering me. Do we pick 4 modules for Wrecking Crew?

**Comment by Stefanos423** [comment]
What I understood from the preview was that each Wrecking Crew member will have their own deck of encounter cards coming with them in the pack and the scenario can it only be played with all 4 of them on the board. And then you can add modules to each of those 4 decks individually.

So, in the app, the Wrecking Crew scenario can be represented by a single image and a single subtitle and the user can still choose the number of side schemes they want to add. If  they choose 1 for example, they choose which deck to add it to.

**Comment by Naouak** [comment]
I've added the support for the option.

For Wrecking Crew, it will add 4 modules, one in each deck. I've added support for multiple encounter decks to show in which deck should each module go.
