### ISSUE TITLE
Add a 'randomize' button further down the page

### ISSUE THREAD

**Issue by mwpower** [Naouak/marvel-lcg-randomizer#41]
Depending on screen-size, its a bit of a pain to have to scroll up/down to re-randomize when I'm looking for a new team to play against a particular scenario.

Having a randomize button in the Players' Deck(s) section would be helpful in this regard.

Alternatively, having a button in both the Players' Deck(s) section and the Scenario section that randomizes *only* that thing, leaving the selection for the other item alone.

**Comment by mwpower** [comment]
Adding a couple of images with a box outlining where I think it'd be useful to have additional randomize buttons.

![IMG_5837](https://user-images.githubusercontent.com/3608183/150425258-8ecce056-3281-484c-b7ad-26084e9f54d3.jpg)
![IMG_5836](https://user-images.githubusercontent.com/3608183/150425266-894c5dd4-741a-496d-8374-d838bcc073d4.jpg)

**Comment by Naouak** [comment]
A "Reroll" button was added at the bottom of the scenario window and decks list. You should be able to see it after refreshing a few times (or a hard refresh).
