### ISSUE TITLE
Permission for forking this project to 'Gitee'

### ISSUE THREAD

**Issue by Haitao61** [Naouak/marvel-lcg-randomizer#68]
Hi Naouak, I'm a Marvel Champions fan from China and I'm now living in Singapore. I recently noticed this project and found it so amazing! I shared this project with our Chinese player group, but they cannot access this GitHub page because Github is blocked in China. In China we have an open source platform called 'Gitee' which is similar to Github, may I have your permission to fork this project to the 'Gitee' platform page? Then Chinese players can also use this amazing randomizer.

**Comment by Naouak** [comment]
Hello,
Yes of course you can, I have not set a licence for the project (as it use visuals I don't own, I'm not sure I can add a licence that would be valid) but you can definitely fork it and use it wherever you want.

**Comment by Haitao61** [comment]
That's nice! Thank you very much！
