### ISSUE TITLE
Pool aspect loading without Deadpool in collection

### ISSUE THREAD

**Issue by Surllio** [Naouak/marvel-lcg-randomizer#73]
Since the last change update, the 'Pool aspect has been generating when random is selected, despite not having Deadpool in my collection.

![Screenshot (23)](https://github.com/Naouak/marvel-lcg-randomizer/assets/142681559/1a6ee5dd-314a-4a88-a6a8-f7522c1098d1)
![Screenshot (24)](https://github.com/Naouak/marvel-lcg-randomizer/assets/142681559/002f64b8-e789-4153-8b12-9601f4fb86fe)

**Comment by Naouak** [comment]
Hey, this should be fixed in the new version I just released. I forgot to implement a filter on aspects based on packs selected. Thanks!
